import * as Shape from "../../../components";

export const addModules = [
  {
    icon: <Shape.Shape1 />,
    title: "CRM-Enrol & Forms",
    desc: "Want to make your admissions process easier? Check out Classe365's CRM-Enrol & Forms module! It helps you streamline enrollment, and create custom forms all in one place.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
  },
  {
    icon: <Shape.Shape5 />,
    title: "Learning Management System",
    desc: "Transform your school with Classe365's easy-to-use Learning Management System. Plan lessons, administer coursework, and improve results with our advanced and effortless platform.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
  },
  {
    icon: <Shape.Shape8 />,
    title: "Fee & Invoicing",
    desc: "With Classe365's Fee & Invoicing feature, you can generate invoices, give parents the option to pay online, and make sure financial transactions go off without a hitch.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
  },
  {
    icon: <Shape.Shape9 />,
    title: "Financial Accounting",
    desc: "Are you ready to take control of your school's finances? Classe365 enables you to keep your books in order, generate statements, reconcile transactions, and stay on top of your finances!",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
  },
  {
    icon: <Shape.Shape7 />,
    title: "Alumni",
    desc: "With Classe365's Alumni module, you can reach out to former students, manage an organised directory of alumni, and create lasting connections for networking and long-term support.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
  },
  {
    icon: <Shape.Shape6 />,
    title: "E-Commerce Store",
    desc: "Unlock a world of opportunities for your school with Classe365's ECommerce Store! Sell products and courses, track inventory, and give students and parents a smooth shopping experience.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
  },
  {
    icon: <Shape.Shape10 />,
    title: "White label",
    desc: "Make Classe365 uniquely yours with our White Label Module! Personalise the platform with your own logo, domain, and styling to deliver a consistent experience for everyone.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
  },
  {
    icon: <Shape.Shape11 />,
    title: "Fund Raising",
    desc: "Make fundraising easy with Classe365! Our platform is your one-stop shop for all of your fundraising and donor management requirements.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
  },
  {
    icon: <Shape.Shape12 />,
    title: "Degree Audit",
    desc: "Track your students' academic progress and give them the support they need to finish their degree with Classe365's Degree Audit! Track their progress and give students a boost on their path to graduation.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
  },
  {
    icon: <Shape.Shape13 />,
    title: "Education Agent Module",
    desc: "Easily build and keep up with your network of education agents using Classe365's Education Agent Module! It's a great way to stay connected and manage your network.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
  },
  {
    icon: <Shape.Shape14 />,
    title: "Enterprise Pro Plan",
    desc: "Classe365's Enterprise Pro Plan gives you access to pro-level features, increased storage space, customisations, and more to help your school reach its full potential.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
  },
];
